/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.juego2eso;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class GameGUI extends javax.swing.JFrame {

    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        System.out.println("asewgfaegdargraegagbtcom.mycompany.juego2eso.JuegoGUI.<init>()");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscenario = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEscenario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelEscenario.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 37, 271, 15));
        panelEscenario.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 70, 186, 17));
        panelEscenario.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 37, 258, 15));
        panelEscenario.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 200, 17));

        jButton1.setText("jButton1");
        panelEscenario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 310, -1, -1));

        jButton3.setText("jButton3");
        panelEscenario.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, -1, -1));

        jButton2.setText("jButton2");
        panelEscenario.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, -1, -1));
        panelEscenario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -340, -1, -1));

        getContentPane().add(panelEscenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JPanel panelEscenario;
    // End of variables declaration//GEN-END:variables
}
