
package com.mycompany.juego2eso;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

 
    public Jugador jugador;
    public Enemigos enemigo;
    public Turnos turnos;
    
    
    public Interfaz() {
        initComponents();
         // Inicializar el juego
        jugador = new Jugador("Jugador", 100, 100, new Armas("Espada", 10, 1, 80, "Normal", 0));
        enemigo = new Enemigos("Enemigo", 100, 100, 80, 10);
        turnos = new Turnos(jugador, enemigo);
        
    }
        //panelEscenario = new Escenario();
        
    
    
    public void actualizarBarrasDeProgreso(int vidaJugador, int vidaEnemigo, int cargaJugador, int cargaEnemigo) {
        VidaJugador.setValue(vidaJugador);
        VidaEnemigo.setValue(vidaEnemigo);
        cargaAtaqueDefinitivoPersonaje.setValue(cargaJugador);
        CargaAtaqueDefinitivoEnemigo.setValue(cargaEnemigo);
    }
    
     private void AtaqueDefinitivoActionPerformed(java.awt.event.ActionEvent evt) {
        // Ejecutar el ataque definitivo del jugador
        int danio = jugador.ataqueDefinitivo(); // Para ataque definitivo
        if (danio > 0) {
            enemigo.recibirdanio(danio);
            JOptionPane.showMessageDialog(this, "Has infligido " + danio + " puntos de daño al enemigo con el ataque definitivo.");
        } else {
            JOptionPane.showMessageDialog(this, "No tienes suficiente carga para usar el ataque definitivo.");
        }
        // Ejecutar el turno del enemigo
         turnos.comenzar();
    }

    private void AtaqueBasicoActionPerformed(java.awt.event.ActionEvent evt) {
        // Ejecutar el ataque básico del jugador
        int danio = jugador.ataqueLigero();
        enemigo.recibirdanio(danio);
        JOptionPane.showMessageDialog(this, "Has infligido " + danio + " puntos de daño al enemigo con el ataque básico.");
        // Ejecutar el turno del enemigo
         turnos.comenzar();
    }

    private void AtaquePesadoActionPerformed(java.awt.event.ActionEvent evt) {
        // Ejecutar el ataque pesado del jugador
        int danio = jugador.ataquePesado(); 
        enemigo.recibirdanio(danio);
        JOptionPane.showMessageDialog(this, "Has infligido " + danio + " puntos de daño al enemigo con el ataque pesado.");
        // Ejecutar el turno del enemigo
         turnos.comenzar();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        panelDeAtaque = new javax.swing.JPanel();
        cargaAtaqueDefinitivoPersonaje = new javax.swing.JProgressBar();
        CargaAtaqueDefinitivoEnemigo = new javax.swing.JProgressBar();
        VidaEnemigo = new javax.swing.JProgressBar();
        VidaJugador = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        ataqueDefinitivo = new javax.swing.JButton();
        ataqueBasico = new javax.swing.JButton();
        ataquePesado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDeAtaque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGeneral.add(panelDeAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 264, -1, -1));

        cargaAtaqueDefinitivoPersonaje.setBackground(new java.awt.Color(255, 255, 153));
        panelGeneral.add(cargaAtaqueDefinitivoPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, 17));

        CargaAtaqueDefinitivoEnemigo.setBackground(new java.awt.Color(153, 153, 0));
        panelGeneral.add(CargaAtaqueDefinitivoEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 54, 168, 13));

        VidaEnemigo.setBackground(new java.awt.Color(153, 0, 0));
        panelGeneral.add(VidaEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 20, 203, 24));

        VidaJugador.setBackground(new java.awt.Color(0, 204, 0));
        panelGeneral.add(VidaJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 162, 22));

        jLabel1.setText("Selecciona un ataque ");
        panelGeneral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        ataqueDefinitivo.setText("jButton1");
        panelGeneral.add(ataqueDefinitivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        ataqueBasico.setText("jButton1");
        panelGeneral.add(ataqueBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        ataquePesado.setText("jButton1");
        panelGeneral.add(ataquePesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/juego2eso/Escenario.jpg"))); // NOI18N
        panelGeneral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar CargaAtaqueDefinitivoEnemigo;
    private javax.swing.JProgressBar VidaEnemigo;
    private javax.swing.JProgressBar VidaJugador;
    private javax.swing.JButton ataqueBasico;
    private javax.swing.JButton ataqueDefinitivo;
    private javax.swing.JButton ataquePesado;
    private javax.swing.JProgressBar cargaAtaqueDefinitivoPersonaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelDeAtaque;
    public javax.swing.JPanel panelGeneral;
    // End of variables declaration//GEN-END:variables
}
